coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch: false
    changes: false

comment: false

fixes:
  - "/home/runner/work/xarray-simlab/xarray-simlab/::"
