name: doc

on:
  pull_request:
    branches:
    - 'master'

jobs:
  doc:
    name: sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          activate-environment: xarray-simlab-doc
          environment-file: ci/requirements/doc.yml
          auto-activate-base: false
      - name: Install RDT sphinx theme
        shell: bash -l {0}
        run: conda install -c conda-forge sphinx_rtd_theme
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Install xarray-simlab
        shell: bash -l {0}
        run: |
          pip install --no-deps -e .
          python -OO -c "import xsimlab"
      - name: Build doc
        shell: bash -l {0}
        run: |
          cd doc
          sphinx-build -n -j auto -b html -d _build/doctrees . _build/html
