name: xarray-simlab-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=18.2.0
  - python=3.6
  - numpy=1.14.5
  - pandas=0.23.3
  - xarray=0.10.9
  - ipython=6.4.0
  - matplotlib=2.2.2
  - graphviz
  - python-graphviz
  - nbconvert=5.2.1
  - sphinx=1.7.6
  - nbsphinx=0.3.3
  - pandoc=1.19.2
